<?php
/**
 * TL_ROOT/system/modules/tags/languages/cs/default.php 
 * 
 * Contao extension: tags 1.7.4 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tags']['0'] = "Tagy";
$GLOBALS['TL_LANG']['MSC']['tags']['1'] = "Zadejte jeden nebo více tagů oddělené čárkou pro kategorizaci.";
$GLOBALS['TL_LANG']['MSC']['notags'] = "Nejsou žádné novinky pro tuto značku.";
$GLOBALS['TL_LANG']['MSC']['emptyarticles'] = "Nejsou žádné články pro tuto značku.";
$GLOBALS['TL_LANG']['MSC']['emptyevents'] = "Nejsou žádné události pro tuto značku.";
 
?>
