<?php
/**
 * TL_ROOT/system/modules/tags/languages/cs/tl_content.php 
 * 
 * Contao extension: tags 3.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['0'] = "Ukázat jen s tagy";
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['1'] = "Zobrazit pouze obsah prvku, pokud je vybraný tag.";
$GLOBALS['TL_LANG']['tl_content']['tags_legend'] = "Tagy";
 
?>
