<?php
/**
 * TL_ROOT/system/modules/tags/languages/cs/tl_settings.php 
 * 
 * Contao extension: tags 3.0.0 stable 
 * Czech translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['0'] = "Zakázat zdroj tagů";
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['1'] = "Zkontrolujte všechny zdrojové tabulky, které by neměly mít vstupní pole pro tag v backend.";
$GLOBALS['TL_LANG']['tl_settings']['tags_legend'] = "Tagy nastavení";
 
?>
