<?php
/**
 * TL_ROOT/system/modules/tags/languages/nl/default.php 
 * 
 * Contao extension: tags 1.7.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tags']['0'] = "Tags";
$GLOBALS['TL_LANG']['MSC']['tags']['1'] = "Geef een of meerdere trefwoorden aan, gescheiden door een komma.";
$GLOBALS['TL_LANG']['MSC']['notags'] = "Geen nieuwsberichten voor dit trefwoord.";
$GLOBALS['TL_LANG']['MSC']['emptyarticles'] = "Geen artikelen voor dit trefwoord.";
$GLOBALS['TL_LANG']['MSC']['emptyevents'] = "Geen gebeurtenissen voor dit trefwoord.";
 
?>
