<?php
/**
 * TL_ROOT/system/modules/tags/languages/nl/modules.php 
 * 
 * Contao extension: tags 1.7.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloud']['0'] = "Tag Cloud";
$GLOBALS['TL_LANG']['FMD']['tagcloud']['1'] = "Deze module toont een tag cloud.";
$GLOBALS['TL_LANG']['FMD']['tagscope']['0'] = "Tag bereik";
$GLOBALS['TL_LANG']['FMD']['tagscope']['1'] = "Deze module toont het bereik van de geselecteerde tags.";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['0'] = "Complete artikellijst";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['1'] = "Deze module toont een lijst met alle artikelen in deze Contao installatie.";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['0'] = "Tag objecten lijst";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['1'] = "Deze module toont een lijst met objecten die bepaalde tags bevatten.";
$GLOBALS['TL_LANG']['FMD']['tags']  = 'Tags';

?>
