<?php
/**
 * TL_ROOT/system/modules/tags/languages/nl/tl_content.php 
 * 
 * Contao extension: tags 1.7.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['0'] = "Toon alleen met tag";
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['1'] = "Toon dit inhoudselement alleen als een tag is geselecteerd.";
$GLOBALS['TL_LANG']['tl_content']['tags_legend'] = "Tags";
 
?>
