<?php
/**
 * TL_ROOT/system/modules/tags/languages/nl/tl_module.php 
 * 
 * Contao extension: tags 1.7.0 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Just Schimmelpenninck (justs) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['0'] = "Ga naar pagina";
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['1'] = "Geef aan naar welke pagina de gebruiker wordt geleid, na het klikken op een tag link.";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['0'] = "Tag tabellen";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['1'] = "Selecteer de tabellen die gebruikt moeten worden om de tag cloud te tonen. Deze selectie is alleen geldig als de <em>tl_tag</em> tabel gebruikt wordt om de tags op te slaan.";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['0'] = "Tag brontabel";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['1'] = "Selecteer de naam van de brontabel waarin de tags gevonden kunnen worden. Dit veld geeft standaard de inhoud van de tabel <em>tl_tag</em>.";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['0'] = "Tag tabelveld";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['1'] = "Selecteer de naam van het tabelveld waarin de tags staan. Dit veld geeft standaard de opgegeven veldnaam <em>tag</em>.";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['0'] = "Tag filter";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['1'] = "Geef een met komma's gescheiden lijst van tags om het resultaat van de module te filteren.";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['0'] = "Maximum aantal tags";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['1'] = "Geef het maximale aantal tags in de tag cloud op. Als de tag cloud meer tags bevat dan dit aantal, zullen de tags met het kleinste aantal hits worden verwijderd. Als u geen waarde of de waarde 0 opgeeft, zullen alle tags getoond worden.";
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']['0'] = "Aantal tag maten";
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']['1'] = "Geef het aantal maten dat in het frontend voor de weergave van de tags wordt gebruikt. Elke tag-groep krijgt zijn eigen maat in het frontend. Deze maten worden als CSS-selectors gegeven: size1, size2, size3 ... size<em>x</em>.";
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']['0'] = "Gebruik tag class name";
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']['1'] = "Voegt een extra CSS class toe voor elke tag. Gebruik deze class name voor extra vormgeving van de tags. Spaties in de tags worden door underscores vervangen in de class names.";
$GLOBALS['TL_LANG']['tl_module']['tag_on_page_class']['0'] = "Tag bestaat op pagina";
$GLOBALS['TL_LANG']['tl_module']['tag_on_page_class']['1'] = "Voegt een extra CSS class ('here') toe voor elke tag die op deze pagina voorkomt.";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['0'] = "Top 10 tags";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['1'] = "Laat een top 10 van tags zien boven de tag cloud.";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['0'] = "Toon gerelateerde tags";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['1'] = "Kies deze optie om alle gerelateerde tags van een eerder geselecteerde tag te tonen.";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['0'] = "Toon nieuws tags";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['1'] = "Kies deze optie om alle toegewezen tags onder elk nieuws-item te tonen. Werkt alleen als u een tag nieuws template zoals news_full_tags gebruikt.";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['0'] = "Negeer tags";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['1'] = "Laat deze module alle tag gerelateerde acties negeren.";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['0'] = "Behoud URL parameters";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['1'] = "Behoud specifieke Contao URL parameters in de tag links.";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['0'] = "Object type";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['1'] = "Kies het object type dat in deze lijst getoond moet worden.";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['0'] = "Tag bron";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['1'] = "Kies de tabel die gebruikt wordt om de tag lijst in deze module te genereren.";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['0'] = "Pagina's";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['1'] = "Kies de pagina's die gebruikt worden om de objectenlijst te maken. Als u een pagina met subpagina's kiest, worden de subpagina's ook gebruikt.";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['0'] = "Artikellijst template";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['1'] = "Kies het template voor de artikellijst.";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['0'] = "Tag cloud template";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['1'] = "Kies het template voor de tag cloud.";
$GLOBALS['TL_LANG']['tl_module']['scope_template']['0'] = "Tag bereik template";
$GLOBALS['TL_LANG']['tl_module']['scope_template']['1'] = "Kies het template voor het bereik van de tags.";
$GLOBALS['TL_LANG']['tl_module']['clear_text']['0'] = "Tag bereik titel";
$GLOBALS['TL_LANG']['tl_module']['clear_text']['1'] = "Geef een titel voor het tag bereik. Deze titel is tevens een link, die het tag bereik en alle geselecteerde tags wist.";
$GLOBALS['TL_LANG']['tl_module']['show_empty_scope']['0'] = "Toon leeg bereik";
$GLOBALS['TL_LANG']['tl_module']['show_empty_scope']['1'] = "Toon het tag bereik, ook al zijn er geen actieve tags.";
$GLOBALS['TL_LANG']['tl_module']['tag_show_reset']['0'] = "Toon wis optie";
$GLOBALS['TL_LANG']['tl_module']['tag_show_reset']['1'] = "Toon een link om alle geselecteerde tags te wissen.";
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']['0'] = "Alleen gefilterd resultaat";
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']['1'] = "De complete artikellijst gaat ervan uit dat een of meerdere tags worden gebruikt om het resultaat te filteren. Zonder een filter, wordt een lege lijst getoond.";
$GLOBALS['TL_LANG']['tl_module']['tag_alltags'] = "Alle tags";
$GLOBALS['TL_LANG']['tl_module']['tag_relatedtags'] = "Gerelateerde tags";
$GLOBALS['TL_LANG']['tl_module']['tl_content'] = "Inhoudselementen";
$GLOBALS['TL_LANG']['tl_module']['tl_article'] = "Artikelen";
$GLOBALS['TL_LANG']['tl_module']['tag_clear_tags'] = "Wis geselecteerde tags";
$GLOBALS['TL_LANG']['tl_module']['tl_page'] = "Pagina's";
$GLOBALS['TL_LANG']['tl_module']['tags'] = "Tags";
$GLOBALS['TL_LANG']['tl_module']['showtags_legend'] = "Tags instellingen";
$GLOBALS['TL_LANG']['tl_module']['tagscope_legend'] = "Tag bereik instellingen";
$GLOBALS['TL_LANG']['tl_module']['size_legend'] = "Aantal en maat instellingen";
$GLOBALS['TL_LANG']['tl_module']['tagextension_legend'] = "Aanvullende tag lijsten";
$GLOBALS['TL_LANG']['tl_module']['datasource_legend'] = "Data bron instellingen";
$GLOBALS['TL_LANG']['tl_module']['object_selection_legend'] = "Object soorten";
 
?>
