<?php
/**
 * TL_ROOT/system/modules/tags/languages/it/default.php 
 * 
 * Contao extension: tags 1.6.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tags']['0'] = "Tag";
$GLOBALS['TL_LANG']['MSC']['tags']['1'] = "Inserire uno o più tag separati da virgola";
$GLOBALS['TL_LANG']['MSC']['notags'] = "Nessuna notizia per questo tag.";
$GLOBALS['TL_LANG']['MSC']['emptyarticles'] = "Nessun articolo per questo tag.";
$GLOBALS['TL_LANG']['MSC']['emptyevents'] = "Nessun evento di calendario per questo tag.";
 
?>
