<?php
/**
 * TL_ROOT/system/modules/tags/languages/it/modules.php 
 * 
 * Contao extension: tags 1.6.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloud']['0'] = "Tag Cloud";
$GLOBALS['TL_LANG']['FMD']['tagcloud']['1'] = "Questo modulo mostra un tag cloud";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['0'] = "Lista globale articoli";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['1'] = "Questo modulo mostra una lista completa degli articoli";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['0'] = "Lista oggetti taggati";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['1'] = "Questo modulo mostra una lista di oggetti contenenti determinati tag";
$GLOBALS['TL_LANG']['FMD']['tags']  = 'Tags';

?>
