<?php
/**
 * TL_ROOT/system/modules/tags/languages/it/tl_content.php 
 * 
 * Contao extension: tags 1.6.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['0'] = "Mostra solamente elementi con tag";
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['1'] = "Mostra questo elemento di contenuto solo quando il tag è selezionato.";
$GLOBALS['TL_LANG']['tl_content']['tags_legend'] = "Tag";
 
?>
