<?php
/**
 * TL_ROOT/system/modules/tags/languages/it/tl_module.php 
 * 
 * Contao extension: tags 1.6.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['0'] = "Salta alla pagina";
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['1'] = "Seleziona la pagina alla quale i visitatori saranno reindirizzati selezionando un tag.";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['0'] = "Tabella tag";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['1'] = "Selezionare le tabelle che vengono utilizzate per mostrare la tag cloud. Questa selezione è valida solo se si utilizza la tabella predefinita <em>tl_tag</em>.";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['0'] = "Tabella sorgente tag";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['1'] = "Selezionare il nome della tabella sorgente dove sono memorizzati i tag. Questo campo è valorizzato di default con il valore <em>tl_tag</em>";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['0'] = "Campo tabella tag";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['1'] = "Indicare il nome del campo della tabella che contiene i tags.  Questo campo è valorizzato di default con il valore <em>tag</em>";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['0'] = "Filtro tag";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['1'] = "Indicare la lista dei tag che si vuole filtrare separati da virgola";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['0'] = "Numero massimo di tag";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['1'] = "Inserisci il numero massimo di tag nel tag cloud. Se la nuvola di tag contiene più tag rispetto al numero massimo di tag, i tag con le hit più piccole verranno rimossi. Se non si immette un valore o il valore è 0, tutti i tag saranno mostrati.";
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']['0'] = "Numero di formati tag";
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']['1'] = "Si prega di inserire il numero di formati di tag che si vuole visualizzare nel frontend. Ogni gruppo di tag avrà il proprio selettore css. I formati CSS di tag sarà del tipo size1, size2, size3 ... size<em>n </em>.";
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']['0'] = "Usa tag per classe css";
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']['1'] = "Aggiunge una classe CSS per ogni tag che contiene il nome del tag. Gli spazi nei nomi dei tag verranno sostituiti da caratteri di sottolineatura nei nomi di classe CSS.";
$GLOBALS['TL_LANG']['tl_module']['tag_on_page_class']['1'] = "Aggiunge una classe ulterior CSS ('here') per ogni tag che è stato assegnato alla pagina effettiva.";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['0'] = "Top 10 Tags";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['1'] = "Mostra la lista dei 10 tag più utilizzati";
$GLOBALS['TL_LANG']['tl_module']['tag_topten_expanded']['0'] = "Espandi Top 10 Tags";
$GLOBALS['TL_LANG']['tl_module']['tag_topten_expanded']['1'] = "Espandi la lista dei 10 tag più utilizzati. Tutti i tag saranno visibili.";
$GLOBALS['TL_LANG']['tl_module']['tag_all_expanded']['0'] = "Espandi tutti i tag";
$GLOBALS['TL_LANG']['tl_module']['tag_all_expanded']['1'] = "Espandi tutti i tag";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['0'] = "Mostra tag correlati";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['1'] = "Questa opzione permette di di mostrare i tag correlati alla precedente selezione.";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['0'] = "Mostra tag news";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['1'] = "Questa opzione permette di visualizzare tutti i tag assegnati sotto ogni voce news. Per utilizare questa opzione selezionare in modello adeguato, per esempio news_full_tags";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['0'] = "Ignora tag";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['1'] = "Forza il modulo ad ignorare i tag correlati";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['0'] = "Mantieni i parametri URL";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['1'] = "Mantieni i parametri URL della pagina";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['0'] = "Tipologia oggetto";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['1'] = "Selezionare il tipo di oggetto che si vuole visualizzare nella lista.";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['0'] = "Sorgente tag";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['1'] = "Selezionare la tabella che si vuole utilizzare come sorgente dei tag";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['0'] = "Pagine";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['1'] = "Selezionare le pagine che vengono utilizzate per costruire la lista degli oggetti. Se si seleziona una pagina che contiene pagine secondarie, tutte le sottopagine saranno elaborate.";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['0'] = "Template lista articoli";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['1'] = "Qui è possibile selezionare il template della lista degli articoli";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['0'] = "Tag cloud template";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['1'] = "Template del Tag cloud";
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']['0'] = "Solo contenuti filtrati";
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']['1'] = "La lista globale degli articoli si aspetta sempre uno o più tag per aveve un output filtrato. Senza filtro di un tag, una lista è vuota.";
$GLOBALS['TL_LANG']['tl_module']['tag_alltags'] = "Tutti i tags";
$GLOBALS['TL_LANG']['tl_module']['tag_relatedtags'] = "Tag correlati";
$GLOBALS['TL_LANG']['tl_module']['tl_content'] = "Elementi di contenuto";
$GLOBALS['TL_LANG']['tl_module']['tl_article'] = "Articoli";
$GLOBALS['TL_LANG']['tl_module']['tl_page'] = "Pagine";
$GLOBALS['TL_LANG']['tl_module']['showtags_legend'] = "Impostazione tag";
$GLOBALS['TL_LANG']['tl_module']['size_legend'] = "Impostazioni quantità e dimensioni";
$GLOBALS['TL_LANG']['tl_module']['tagextension_legend'] = "Lista tag aggiuntivi";
$GLOBALS['TL_LANG']['tl_module']['datasource_legend'] = "Impostazioni sorgente dati";
$GLOBALS['TL_LANG']['tl_module']['object_selection_legend'] = "Tipologia oggetto";
 
?>
