<?php
/**
 * TL_ROOT/system/modules/tags/languages/it/tl_settings.php 
 * 
 * Contao extension: tags 1.6.6 stable 
 * Italian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Paolo Brunelli (PaoloB), http://www.contaocms.it 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['0'] = "Disabilita tabella sorgente tag";
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['1'] = "Disabilita l'utilizzo di tabelle personalizzate. Si consiglia di controllare tutte le tabelle di origine che non dovrebbero avere un campo di input tag nel backend.";
$GLOBALS['TL_LANG']['tl_settings']['tags_legend'] = "Impostazioni tags";
 
?>
