<?php 

/**
 * TL_ROOT/system/modules/tags/languages/fr/default.php 
 * 
 * Contao extension: tags
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MSC']['tags']     = array('Tags', 'Veuillez entrer un ou plusieurs tags séparés par des virgules pour la catégorisation.');
$GLOBALS['TL_LANG']['MSC']['notags']   = 'Aucune actualité pour ce tag.';
$GLOBALS['TL_LANG']['MSC']['emptyarticles']   = 'Il n\'y a pas d\'articles pour ce tag.';
$GLOBALS['TL_LANG']['MSC']['emptyevents']   = 'Il n\'y a aucun événement pour ce tag.';



?>