<?php

/**
 * TL_ROOT/system/modules/tags/languages/fr/modules.php 
 * 
 * Contao extension: tags
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Back end modules
 */


/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['tagcloud']    = array('Nuage de tags', 'Ce module affiche un nuage de tags.');
$GLOBALS['TL_LANG']['FMD']['tagscope']    = array('Portée des tags', 'Ce module affiche la portée des tags sélectionnées.');
$GLOBALS['TL_LANG']['FMD']['globalArticleList']    = array('Liste d\'articles globale', 'Ce module affiche une liste d\'articles de l\'installation complète de Contao.');
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']    = array('Liste d\'objets de tags', 'Ce module affiche une liste d\'objets contenant un ensemble de tags.');
$GLOBALS['TL_LANG']['FMD']['taglistbycategory'] = array('Liste de tags par catégorie', 'Ce module affiche une liste d\'objets pour un tag spécifique qui est classée par les sources des tags.');
$GLOBALS['TL_LANG']['FMD']['tags']  = 'Tags';

// articles

$GLOBALS['TL_LANG']['FMD']['tagcloudarticles']    = array('Nuage de tags (Articles)', 'Ce module affiche un nuage de tags pour les articles sélectionnés.');
$GLOBALS['TL_LANG']['FMD']['taggedArticleList']   = array('Liste d\'articles (Tags)', 'Ce module génère une liste d\'articles d\'une colonne dans une sous-arborescence sélectionnée et peut être filtrée par un nuage de tags.');

// content

$GLOBALS['TL_LANG']['FMD']['tagcloudcontent']    = array('Nuage de tags (Éléments de contenu)', 'Ce module affiche un nuage de tags pour les éléments de contenu sélectionnés.');

// events

$GLOBALS['TL_LANG']['FMD']['tagcloudevents']    = array('Nuage de tags (Événements)', 'Ce module affiche un nuage de tags pour les événements du calendrier.');

// members

$GLOBALS['TL_LANG']['FMD']['tagcloudmembers']    = array('Nuage de tags (Membres)', 'Ce module affiche un nuage de tags pour les groupes de membres sélectionnés.');

// news

$GLOBALS['TL_LANG']['FMD']['tagcloudnews']    = array('Nuage de tags (Actualités)', 'Ce module affiche un nuage de tags pour les actualités`.');

?>
