<?php
/**
 * TL_ROOT/system/modules/tags/languages/ja/default.php 
 * 
 * Contao extension: tags 1.7.4 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tags']['0'] = "タグ";
$GLOBALS['TL_LANG']['MSC']['tags']['1'] = "分類するための1つ以上のタグをコンマで区切って入力してください。";
$GLOBALS['TL_LANG']['MSC']['notags'] = "このタグのニュース項目はありません。";
$GLOBALS['TL_LANG']['MSC']['emptyarticles'] = "このタグのアーティクルはありません。";
$GLOBALS['TL_LANG']['MSC']['emptyevents'] = "このタグのイベントはありません。";
 
?>
