<?php
/**
 * TL_ROOT/system/modules/tags/languages/ja/modules.php 
 * 
 * Contao extension: tags 1.7.4 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloud']['0'] = "タグクラウド";
$GLOBALS['TL_LANG']['FMD']['tagcloud']['1'] = "このモジュールはタグクラウドを表示します。";
$GLOBALS['TL_LANG']['FMD']['tagscope']['0'] = "タグスコープ";
$GLOBALS['TL_LANG']['FMD']['tagscope']['1'] = "このモジュールは選択しているタグの範囲を表示します。";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['0'] = "全体的なアーティクルのリスト";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['1'] = "このモジュールはインストールしているContaoのアーティクルの完全な一覧を表示します。";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['0'] = "タグのオブジェクトのリスト";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['1'] = "このモジュールはタグ一式を含んでいるオブジェクトの一覧を表示します。";
$GLOBALS['TL_LANG']['FMD']['taglistbycategory']['0'] = "カテゴリー別タグリスト";
$GLOBALS['TL_LANG']['FMD']['taglistbycategory']['1'] = "このモジュールはタグのソースで分類した特定のタグの、オブジェクトのリストを表示します。";
$GLOBALS['TL_LANG']['FMD']['tags'] = "タグ";
 
?>
