<?php
/**
 * TL_ROOT/system/modules/tags/languages/ja/tl_content.php 
 * 
 * Contao extension: tags 1.7.4 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['0'] = "タグの選択時だけ表示";
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['1'] = "タグを選択しているときだけ、このコンテンツ要素を表示します。";
$GLOBALS['TL_LANG']['tl_content']['tags_legend'] = "タグ";
 
?>
