<?php
/**
 * TL_ROOT/system/modules/tags/languages/ja/tl_module.php 
 * 
 * Contao extension: tags 1.7.4 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['0'] = "ページに移動";
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['1'] = "この設定はタグのリンクをクリックしたときに移動する先のページを指定します。";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['0'] = "タグのテーブル";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['1'] = "タグクラウドを表示するのに使用するテーブルを選択してください。ここでの選択は、予め定義済みのテーブル<em>tl_tag</em>をタグの保存に使用する場合だけ有効です。";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['0'] = "タグのソースのテーブル";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['1'] = "タグをみつけるソースのテーブルの名前を入力してください。この項目の初期値は予め定義済みのテーブル<em>tl_tag</em>です。";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['0'] = "タグのテーブルの項目";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['1'] = "タグを保持するテーブルの項目の名前を入力してください。この項目の初期値は予め定義済みの項目<em>tag</em>です。";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['0'] = "タグのフィルター";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['1'] = "モジュールの出力を絞り込む、コンマで区切ったタグのリストを入力してください。";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['0'] = "タグの最大数";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['1'] = "タグクラウドに含める、タグの数の最大値を入力してください。この値よりも多くのタグがタグクラウドにあると、数の少ないタグをタグクラウドに表示しません。値を入力しないか0にすると、すべてのタグを表示します。";
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']['0'] = "タグの大きさの数";
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']['1'] = "フロントエンドのタグの大きさの数を入力してください。フロントエンドでは、タグの各グループには独自のタグの大きさがあります。タグの大きさはCSSのセレクターにsize1, size2, size3, size<em>n</em>と反映します。";
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']['0'] = "タグのクラス名を使用";
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']['1'] = "追加のCSSのクラスを、タグ名を含むすべてのタグのCSSのクラスに追加します。この追加のクラス名は、CSSでタグの表示スタイルを追加するために使用してください。タグの名前のスペースがあると、CSSのクラス名ではアンダースコアに置き換えます。";
$GLOBALS['TL_LANG']['tl_module']['tag_on_page_class']['0'] = "ページに存在するタグ";
$GLOBALS['TL_LANG']['tl_module']['tag_on_page_class']['1'] = "実際のページに割り当てられた各タグに、追加のCSSのクラス('here')を追加します。";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['0'] = "トップテンのタグ";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['1'] = "タグクラウドに上位10位のタグを表示します。";
$GLOBALS['TL_LANG']['tl_module']['tag_topten_expanded']['0'] = "タグクラウドに上位10位のタグを表示します。";
$GLOBALS['TL_LANG']['tl_module']['tag_topten_expanded']['1'] = "トップテンのタグクラウドを展開します。トップテンのすべてのタグを表示した状態にします。";
$GLOBALS['TL_LANG']['tl_module']['tag_all_expanded']['0'] = "すべてのタグを展開";
$GLOBALS['TL_LANG']['tl_module']['tag_all_expanded']['1'] = "「すべてのタグ」のタグクラウドを展開します。すべてのタグのすべてのタグを表示した状態にします。";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['0'] = "関係するタグを表示";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['1'] = "これを選択すると、前に選択したタグに関連したすべてのタグを表示します。";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['0'] = "ニュースのタグを表示";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['1'] = "これを選択すると、各ニュース項目に割り当てられたすべてのタグを表示します。これはタグを有効にしたニュースのテンプレート(例えば、news_full_tags)だけで動作します。";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['0'] = "無視するタグ";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['1'] = "このモジュールではタグに関連した動作(例えば、指定したタグのニュース項目だけを表示するといった)を強制的に無視します。";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['0'] = "URLのパラメーターを維持";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['1'] = "タグのリンクでContao特有のURLのパラメーター(例えば、ニュースアーカイブの日付)の指定を保持します。";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['0'] = "オブジェクトの種類";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['1'] = "このリストに表示するオブジェクトの種類を選択してください。";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['0'] = "タグのソース";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['1'] = "このモジュールでタグのリストを作成するのに使用するテーブルを選択してください。";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['0'] = "ページ";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['1'] = "オブジェクトリストを作成するのに使用するページを選択してください。下位のページがあるページを選択すると、すべての下位のページも使用します。";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['0'] = "アーティクルリストのテンプレート";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['1'] = "アーティクルリストのテンプレートを選択できます。";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['0'] = "タグクラウドのテンプレート";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['1'] = "タグクラウドのテンプレートを選択できます。";
$GLOBALS['TL_LANG']['tl_module']['scope_template']['0'] = "タグスコープのテンプレート";
$GLOBALS['TL_LANG']['tl_module']['scope_template']['1'] = "タグスコープのテンプレートを選択できます。";
$GLOBALS['TL_LANG']['tl_module']['clear_text']['0'] = "タグスコープの見出し";
$GLOBALS['TL_LANG']['tl_module']['clear_text']['1'] = "タグスコープの見出しを入力してください。この見出しはタグスコープを消去して、すべての選択中のタグを消去するハイパーリンクとなります。";
$GLOBALS['TL_LANG']['tl_module']['show_empty_scope']['0'] = "空のスコープを表示";
$GLOBALS['TL_LANG']['tl_module']['show_empty_scope']['1'] = "有効なタグがない場合でもタグスコープを表示します。";
$GLOBALS['TL_LANG']['tl_module']['tag_show_reset']['0'] = "選択を解除するオプション";
$GLOBALS['TL_LANG']['tl_module']['tag_show_reset']['1'] = "選択しているタグを解除するハイパーリンクを表示します。";
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']['0'] = "フィルターした出力に限定";
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']['1'] = "常に1つ以上のタグの選択が全体的なアーティクルのリストの表示に必要にします。タグの選択がないと空のリストを表示します。";
$GLOBALS['TL_LANG']['tl_module']['tag_alltags'] = "すべてのタグ";
$GLOBALS['TL_LANG']['tl_module']['tag_relatedtags'] = "関連するタグ";
$GLOBALS['TL_LANG']['tl_module']['tl_content'] = "コンテンツ要素";
$GLOBALS['TL_LANG']['tl_module']['tl_article'] = "アーティクル";
$GLOBALS['TL_LANG']['tl_module']['tl_news'] = "ニュース記事";
$GLOBALS['TL_LANG']['tl_module']['tag_clear_tags'] = "タグの選択を消去";
$GLOBALS['TL_LANG']['tl_module']['tl_calendar_events'] = "イベント";
$GLOBALS['TL_LANG']['tl_module']['tl_page'] = "ページ";
$GLOBALS['TL_LANG']['tl_module']['tags'] = "タグ";
$GLOBALS['TL_LANG']['tl_module']['showtags_legend'] = "タグの設定";
$GLOBALS['TL_LANG']['tl_module']['tagscope_legend'] = "タグスコープの設定";
$GLOBALS['TL_LANG']['tl_module']['size_legend'] = "数と大きさの設定";
$GLOBALS['TL_LANG']['tl_module']['tagextension_legend'] = "追加するタグのリスト";
$GLOBALS['TL_LANG']['tl_module']['datasource_legend'] = "データソースの設定";
$GLOBALS['TL_LANG']['tl_module']['object_selection_legend'] = "オブジェクトの種類";
 
?>
