<?php
/**
 * TL_ROOT/system/modules/tags/languages/ja/tl_settings.php 
 * 
 * Contao extension: tags 1.7.4 stable 
 * Japanese translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['0'] = "使用しないタグのソースのテーブル";
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['1'] = "バックエンドでタグの入力欄を必要としないテーブルをすべて選択してください。";
$GLOBALS['TL_LANG']['tl_settings']['tags_legend'] = "タグの設定";
 
?>
