<?php
/**
 * TL_ROOT/system/modules/tags/languages/de/default.php 
 * 
 * Contao extension: tags
 * German translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tags']['0'] = "Auszeichnungen";
$GLOBALS['TL_LANG']['MSC']['tags']['1'] = "Bitte geben Sie eine oder mehrere Auszeichnungen durch Komma getrennt an, um eine Kategorisierung vorzunehmen.";
$GLOBALS['TL_LANG']['MSC']['notags'] = "Keine Nachrichtenbeiträge für diese Auszeichnung vorhanden.";
$GLOBALS['TL_LANG']['MSC']['emptyarticles'] = "Es sind keine Artikel für diese Auszeichnung vorhanden.";
$GLOBALS['TL_LANG']['MSC']['emptyevents'] = "Es sind keine Ereignisse für diese Auszeichnung vorhanden.";
 
?>
