<?php
/**
 * TL_ROOT/system/modules/tags/languages/de/modules.php 
 * 
 * Contao extension: tags 1.6.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloud']['0'] = "Tag Cloud";
$GLOBALS['TL_LANG']['FMD']['tagcloud']['1'] = "Dieses Modul zeigt eine Liste mit Auszeichnungen (Tag Cloud) an.";
$GLOBALS['TL_LANG']['FMD']['tagscope']['0'] = 'Verwendete Auszeichnungen';
$GLOBALS['TL_LANG']['FMD']['tagscope']['1'] = 'Diese Modul zeigt die aktuell verwendeten Auszeichnungen an.';
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['0'] = "Globale Artikelliste";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['1'] = "Dieses Modul erzeugt eine Liste aller vorhandener Artikel der Contao-Installation.";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['0'] = "Auszeichnungsobjekte";
$GLOBALS['TL_LANG']['FMD']['tagcontentlist']['1'] = "Dieses Modul erzeugt eine Liste von Objekten, die bestimmte Auszeichnungen beinhalten.";
$GLOBALS['TL_LANG']['FMD']['taglistbycategory']['0'] = 'Kategorisierte Auszeichnungsliste';
$GLOBALS['TL_LANG']['FMD']['taglistbycategory']['1'] = 'Dieses Modul erzeugt eine Liste aller Objekte zu einer ausgewählten Auszeichnung, kategorisiert nach den Auszeichnungs-Quellen.';
$GLOBALS['TL_LANG']['FMD']['tags']  = 'Auszeichnungen';

?>
