<?php
/**
 * TL_ROOT/system/modules/tags/languages/de/tl_content.php 
 * 
 * Contao extension: tags 1.6.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['0'] = "Nur bei Auszeichnungen anzeigen";
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['1'] = "Dieses Inhaltselement nur anzeigen, wenn Auszeichnungen verwendet werden.";
$GLOBALS['TL_LANG']['tl_content']['tags_legend'] = "Auszeichnungen";
 
?>
