<?php
/**
 * TL_ROOT/system/modules/tags/languages/de/tl_member.php
 *
 * Contao extension: tags
 * German translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_member']['categories_legend'] = "Kategorien";
