<?php
/**
 * TL_ROOT/system/modules/tags/languages/de/tl_settings.php 
 * 
 * Contao extension: tags 1.6.5 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['0'] = "Deaktivierte Auszeichnungs-Quellen";
$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']['1'] = "Wählen Sie alle Datentabellen aus, bei denen kein Auszeichnungs-Eingabefeld im Backend verfügbar sein soll.";
$GLOBALS['TL_LANG']['tl_settings']['tags_legend'] = "Auszeichnungs-Einstellungen";
 
?>
