<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/default.php 
 * 
 * Contao extension: tags 1.6.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['tags']['0'] = "Mots clés (Tags)";
$GLOBALS['TL_LANG']['MSC']['tags']['1'] = "Pour la catégorisation, saisir un ou plusieurs mots clés séparés  par des virgules.";
$GLOBALS['TL_LANG']['MSC']['notags'] = "Il n'y a aucune actualité pour ce mot clé.";
$GLOBALS['TL_LANG']['MSC']['emptyarticles'] = "Il n'y a aucun article pour ce mot clé.";
$GLOBALS['TL_LANG']['MSC']['emptyevents'] = "Il n'y a aucun évènement pour ce mot clé.";
 
?>
