<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/modules.php
 *
 * Contao extension: tags
 * French translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS["TL_LANG"]["FMD"]["tagcloud"]["0"] = "Nuage de mots-clés";
$GLOBALS["TL_LANG"]["FMD"]["tagcloud"]["1"] = "Ce module affiche une liste de mots-clés (nuage de mots-clés).";
$GLOBALS["TL_LANG"]["FMD"]["tagscope"]["0"] = "Mots clés utilisés";
$GLOBALS["TL_LANG"]["FMD"]["tagscope"]["1"] = "Ce module affiche les mots-clés actuellement utilisés.";
$GLOBALS["TL_LANG"]["FMD"]["globalArticleList"]["0"] = "Liste globale des articles";
$GLOBALS["TL_LANG"]["FMD"]["globalArticleList"]["1"] = "Ce module génère une liste de tous les articles existants de l'installation Contao.";
$GLOBALS["TL_LANG"]["FMD"]["tagcontentlist"]["0"] = "Objets mots-clés";
$GLOBALS["TL_LANG"]["FMD"]["tagcontentlist"]["1"] = "Ce module génère une liste d'objets contenant des mots-clés spécifiques.";
$GLOBALS["TL_LANG"]["FMD"]["taglistbycategory"]["0"] = "Liste de mots clés classés par catégorie";
$GLOBALS["TL_LANG"]["FMD"]["taglistbycategory"]["1"] = "Ce module génère une liste de tous les objets relatifs à un mot-clé sélectionné, catégorisés selon les sources du mot-clé.";
$GLOBALS["TL_LANG"]["FMD"]["tags"]  = "Mots clés";

// articles

$GLOBALS["TL_LANG"]["FMD"]["tagcloudarticles"]["0"] = "Nuage de mots-clés (article)";
$GLOBALS["TL_LANG"]["FMD"]["tagcloudarticles"]["1"] = "Ce module crée un nuage de mots-clés pour les articles Contao.";
$GLOBALS["TL_LANG"]["FMD"]["taggedArticleList"]["0"] = "Liste d'articles (Mots clés)";
$GLOBALS["TL_LANG"]["FMD"]["taggedArticleList"]["1"] = "Ce module crée une liste d'articles Contao et limite éventuellement l'affichage à une colonne spécifique d'un modèle de page et ne répond qu'aux appels depuis un nuage de mots-clés.";

// content

$GLOBALS["TL_LANG"]["FMD"]["tagcloudcontent"]["0"] = "Tag Cloud (Inhaltselemente)";
$GLOBALS["TL_LANG"]["FMD"]["tagcloudcontent"]["1"] = "Dieses Modul erstellt eine Tag Cloud für Inhaltselemente in einem Contao Unterbereich.";

// events

$GLOBALS["TL_LANG"]["FMD"]["tagcloudevents"]["0"] = "Nuage de mots-clés (Événements)";
$GLOBALS["TL_LANG"]["FMD"]["tagcloudevents"]["1"] = "Ce module affiche un nuage de mots-clés pour les entrées de calendrier.";

// members

$GLOBALS["TL_LANG"]["FMD"]["tagcloudmembers"]["0"] = "Nuage de mots-clés (Membres)";
$GLOBALS["TL_LANG"]["FMD"]["tagcloudmembers"]["1"] = "Ce module affiche un nuage de mots-clés pour les membres.";

// news

$GLOBALS["TL_LANG"]["FMD"]["tagcloudnews"]["0"] = "Nuage de mots-clés (Nouvelles)";
$GLOBALS["TL_LANG"]["FMD"]["tagcloudnews"]["1"] = "Ce module affiche une liste de distinctions (nuage de mots-clés) pour les articles d'actualité.";

?>
