<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/modules.php 
 * 
 * Contao extension: tags 1.6.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['FMD']['tagcloud']['0'] = "Nuage de mots clés";
$GLOBALS['TL_LANG']['FMD']['tagcloud']['1'] = "Affiche un nuage de mot clés";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['0'] = "Liste globale d'articles";
$GLOBALS['TL_LANG']['FMD']['globalArticleList']['1'] = "Affiche la liste de tous les articles.";
$GLOBALS['TL_LANG']['FMD']['tags']  = 'Mots clés';

?>
