<?php

/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_article.php 
 * 
 * Contao extension: tags
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_article']['tags_jumpto']         = array('Aller à la page', 'Ce paramètre définit vers quelle page un utilisateur sera redirigé en cliquant sur un tag.');
$GLOBALS['TL_LANG']['tl_article']['tags_max_tags']       = array('Nombre maximal de tags', 'Veuillez entrer le nombre maximum de tags qui doivent être affichés pour l\'article. Si le nombre est 0, tous les tags seront affichés.');
$GLOBALS['TL_LANG']['tl_article']['tags_showtags']       = array('Afficher les tags', 'Sélectionnez cette option pour afficher les tags attribués à l`\'article.');
$GLOBALS['TL_LANG']['tl_article']['tags_relevance']      = array('Trier par pertinence', 'Sélectionnez cette option pour trier les balises attribuées par pertinence. Si elle n\'est pas cochée, les tags seront triés par ordre alphabétique.');
$GLOBALS['TL_LANG']['tl_article']['tags']                = "Tags";

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_article']['tags_legend']         = 'Tags';

?>