<?php if (!defined("TL_ROOT")) die("You can not access this file directly!");

/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_article.php
 *
 * Contao extension: tags
 * French translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */


/**
 * Fields
 */
$GLOBALS["TL_LANG"]["tl_article"]["tags_jumpto"]         = array("Redirection vers la page", "Ce paramètre permet de définir la page vers laquelle un utilisateur est redirigé après avoir cliqué sur un mot-clé.");
$GLOBALS["TL_LANG"]["tl_article"]["tags_max_tags"]       = array("Nombre maximum de mots-clés", "Indiquez le nombre maximal de mots-clés qui doivent être affichés pour cet article. Si le nombre maximal est égal à 0, tous les mots-clés seront affichés.");
$GLOBALS["TL_LANG"]["tl_article"]["tags_showtags"]       = array("Afficher les mots du bol", "Sélectionnez cette option pour afficher les mots-clés associés à cet article.");
$GLOBALS["TL_LANG"]["tl_article"]["tags_relevance"]      = array("Trier par pertinence", "Sélectionnez cette option pour trier les mots-clés associés à cet article par pertinence (fréquence d"occurrence). Si cette option n"est pas sélectionnée, les mots-clés sont triés par ordre alphabétique.");
$GLOBALS["TL_LANG"]["tl_article"]["tags"]                = "Mots clés";

/**
 * Legends
 */
$GLOBALS["TL_LANG"]["tl_article"]["tags_legend"]         = "Mots clés";

?>