<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_content.php
 *
 * Contao extension: tags
 * French translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */
 
$GLOBALS["TL_LANG"]["tl_content"]["tagsonly"]["0"] = "Afficher uniquement pour les mots-clés";
$GLOBALS["TL_LANG"]["tl_content"]["tagsonly"]["1"] = "N'afficher cet élément de contenu que si des mots-clés sont utilisés.";
$GLOBALS["TL_LANG"]["tl_content"]["tag_filter"]["0"] = "Filtre de mots-clés";
$GLOBALS["TL_LANG"]["tl_content"]["tag_filter"]["1"] = "Spécifiez une liste de mots-clés séparés par des virgules afin de limiter la sortie de l'élément de contenu aux mots-clés spécifiés.";
$GLOBALS["TL_LANG"]["tl_content"]["tag_ignore"]["0"] = "Ignorer les mots-clés";
$GLOBALS["TL_LANG"]["tl_content"]["tag_ignore"]["1"] = "Le module ignore tous les mots-clés (par ex. le filtrage par mots-clés)";
$GLOBALS["TL_LANG"]["tl_content"]["tags_legend"] = "Mots clés";
 
?>
