<?php

/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_content.php 
 * 
 * Contao extension: tags
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_content']['tagsonly']        = array('Afficher uniquement avec les tags', 'Afficher uniquement cet élément de contenu lorsqu\'un balisetag est sélectionné.');
$GLOBALS['TL_LANG']['tl_content']['tag_filter']      = array('Filtre de tags', 'Veuillez entrer une liste de balises séparées par des virgules pour filtrer les éléments de contenu.');
$GLOBALS['TL_LANG']['tl_content']['tag_ignore']      = array('Ignorer les tags', 'Forcer ce module à ignorer les actions liées aux tags (e.g. Afficher uniquement le contenu avec le tag selectionné)');

$GLOBALS['TL_LANG']['tl_content']['tags_legend']     = "Tags";

?>