<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_content.php 
 * 
 * Contao extension: tags 1.6.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['tagsonly']['0'] = "Afficher seulement avec les mots clés";
$GLOBALS['TL_LANG']['tl_content']['tags_legend'] = "Mots clés";
 
?>
