<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_module.php 
 * 
 * Contao extension: tags 1.6.4 stable 
 * French translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Cyril Ponce (cyril), http://www.contao.fr 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']['0'] = "Aller à la page";
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']['0'] = "Tables de mots clés";
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']['0'] = "Table";
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']['0'] = "Champ";
$GLOBALS['TL_LANG']['tl_module']['tag_filter']['0'] = "Filtre";
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']['0'] = "Nombre maximum de mots clés";
$GLOBALS['TL_LANG']['tl_module']['tag_topten']['0'] = "Top 10";
$GLOBALS['TL_LANG']['tl_module']['tag_related']['0'] = "Afficher les mots clés relatifs";
$GLOBALS['TL_LANG']['tl_module']['news_showtags']['0'] = "Afficher les mots clés";
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']['0'] = "Ignorer des mots clés";
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']['0'] = "Garder les paramètres de l'URL";
$GLOBALS['TL_LANG']['tl_module']['objecttype']['0'] = "Type d'objet";
$GLOBALS['TL_LANG']['tl_module']['tagsource']['0'] = "Source des mots clés";
$GLOBALS['TL_LANG']['tl_module']['pagesource']['0'] = "Pages";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['0'] = "Modèle de la liste d'article";
$GLOBALS['TL_LANG']['tl_module']['articlelist_template']['1'] = "Sélectionnez un modèle";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['0'] = "Modèle du nuage de mots clés";
$GLOBALS['TL_LANG']['tl_module']['cloud_template']['1'] = "Sélectionnez un modèle";
$GLOBALS['TL_LANG']['tl_module']['tag_alltags'] = "Tous les mots clés";
$GLOBALS['TL_LANG']['tl_module']['tag_relatedtags'] = "Mots clés relatifs";
$GLOBALS['TL_LANG']['tl_module']['tl_content'] = "Eléments de contenu";
$GLOBALS['TL_LANG']['tl_module']['tl_article'] = "Articles";
$GLOBALS['TL_LANG']['tl_module']['tl_page'] = "Pages";
$GLOBALS['TL_LANG']['tl_module']['showtags_legend'] = "Paramètres des mots clés";
$GLOBALS['TL_LANG']['tl_module']['size_legend'] = "Paramètres du nombre et de la taille";
$GLOBALS['TL_LANG']['tl_module']['tagextension_legend'] = "Listes additionnelles de mots clés";
$GLOBALS['TL_LANG']['tl_module']['datasource_legend'] = "Paramètres de la source de données";
$GLOBALS['TL_LANG']['tl_module']['object_selection_legend'] = "Types d'objets";
 
?>
