<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_module.php
 *
 * Contao extension: tags
 * French translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS["TL_LANG"]["tl_module"]["tag_jumpTo"]["0"] = "Redirection vers la page";
$GLOBALS["TL_LANG"]["tl_module"]["tag_jumpTo"]["1"] = "Ce paramètre permet de définir la page vers laquelle un utilisateur est redirigé après avoir cliqué sur un mot-clé.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_forTable"]["0"] = "Limitation à la (aux) table(s)";
$GLOBALS["TL_LANG"]["tl_module"]["tag_forTable"]["1"] = "Wählen Sie bitte die Tabellen aus, auf die die Auswahl der Schlüsselwörter beschränkt werden soll. Ce paramètre n'est utilisé que si vous utilisez la table prédéfinie <em>tl_tag</em> pour enregistrer les mots-clés.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_tagtable"]["0"] = "Tableau source pour les mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_tagtable"]["1"] = "Veuillez indiquer le nom d'une table à partir de laquelle les mots-clés enregistrés peuvent être récupérés. Le nom par défaut est la table prédéfinie <em>tl_tag</em>.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_tagfield"]["0"] = "Zone de tableau pour les récompenses";
$GLOBALS["TL_LANG"]["tl_module"]["tag_tagfield"]["1"] = "Veuillez indiquer le nom d'un champ de table à partir duquel la sélection des mots-clés doit être générée. Le champ de table prédéfini <em>tag</em> est le champ par défaut.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_filter"]["0"] = "Filtre de mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_filter"]["1"] = "Spécifiez une liste de mots-clés séparés par des virgules pour limiter la sortie du module aux messages contenant les mots-clés spécifiés.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_maxtags"]["0"] = "Nombre maximum de mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_maxtags"]["1"] = "Indiquez un nombre maximal de mots-clés à afficher dans le nuage de mots-clés. S'il y a plus de mots-clés que ce qui peut être affiché, les mots-clés qui apparaissent le moins sont retirés de la liste. Si vous indiquez 0 ou aucune valeur, tous les mots-clés seront affichés.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_buckets"]["0"] = "Nombre de tailles de mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_buckets"]["1"] = "Indiquez le nombre de tailles de mots-clés pour le frontend. Chaque taille de mot-clé représente une possibilité de mise en forme pour une classe de mots-clés. Les tailles de balisage sont présentées sous forme de sélecteurs CSS size1, size2, size3 ... size<em>n</em>.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_named_class"]["0"] = "Utiliser les noms de classe des mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_named_class"]["1"] = "Ajoute un nom de classe CSS supplémentaire pour chaque mot-clé, composé du nom du mot-clé en question. Cela permet d'adapter individuellement les différents mots-clés par CSS. Les espaces dans les noms de mots-clés sont convertis en traits de soulignement pour les noms de classe CSS.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_on_page_class"]["0"] = "Mot-clé sur la page actuelle";
$GLOBALS["TL_LANG"]["tl_module"]["tag_on_page_class"]["1"] = "Ajoute un nom de classe CSS supplémentaire (&quot;here&quot;) pour chaque mot-clé attribué à la page en cours.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_topten"]["0"] = "Mots clés les plus fréquents";
$GLOBALS["TL_LANG"]["tl_module"]["tag_topten"]["1"] = "afficher les mots-clés les plus fréquents au-dessus du nuage de mots-clés.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_topten_number"]["0"] = "Nombre de mots-clés les plus fréquents";
$GLOBALS["TL_LANG"]["tl_module"]["tag_topten_number"]["1"] = "Indiquez le nombre maximal de mots-clés les plus fréquemment utilisés qui doivent être édités.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_topten_expanded"]["0"] = "Les mots-clés les plus fréquents sont dépliés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_topten_expanded"]["1"] = "Le nuage de mots-clés avec les mots-clés les plus fréquents est ouvert, ce qui signifie que tous les mots-clés qu'il contient sont visibles.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_all_expanded"]["0"] = "Tous les mots-clés sont développés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_all_expanded"]["1"] = "Le nuage de mots-clés avec tous les mots-clés est ouvert, c'est-à-dire que tous les mots-clés qu'il contient sont visibles.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_related"]["0"] = "Mots-clés associés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_related"]["1"] = "Sélectionnez cette option pour afficher, pour un mot-clé sélectionné, les mots-clés associés à ce mot-clé dans une liste.";
$GLOBALS["TL_LANG"]["tl_module"]["news_showtags"]["0"] = "Afficher les mots-clés des messages";
$GLOBALS["TL_LANG"]["tl_module"]["news_showtags"]["1"] = "Sélectionnez cette option pour afficher les mots-clés associés à une actualité en dessous de celle-ci. Cette option n'est efficace que si vous utilisez un modèle adapté à l'affichage des mots-clés, par exemple news_full_tags.";
$GLOBALS["TL_LANG"]["tl_module"]["event_showtags"]["0"] = "Afficher les mots-clés des événements";
$GLOBALS["TL_LANG"]["tl_module"]["event_showtags"]["1"] = "Sélectionnez cette option pour afficher les mots-clés associés à un événement sous l'événement. Cette option n'est efficace que si vous utilisez un modèle adapté à l'affichage des mots-clés, par exemple event_..._tags.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_ignore"]["0"] = "Ignorer les mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_ignore"]["1"] = "Le module ignore tous les mots-clés (par ex. le filtrage des listes de messages par mots-clés)";
$GLOBALS["TL_LANG"]["tl_module"]["keep_url_params"]["0"] = "Obtenir des paramètres URL";
$GLOBALS["TL_LANG"]["tl_module"]["keep_url_params"]["1"] = "Obtenir des paramètres d'URL spécifiques à Contao (par exemple, les dates pour les archives d'actualités) dans les liens Tag Cloud";
$GLOBALS["TL_LANG"]["tl_module"]["objecttype"]["0"] = "Type d'objet";
$GLOBALS["TL_LANG"]["tl_module"]["objecttype"]["1"] = "Veuillez sélectionner le type d'objet à afficher.";
$GLOBALS["TL_LANG"]["tl_module"]["tagsource"]["0"] = "Limitation à la source de données";
$GLOBALS["TL_LANG"]["tl_module"]["tagsource"]["1"] = "Veuillez sélectionner le tableau auquel la sélection des mots-clés doit être limitée.";
$GLOBALS["TL_LANG"]["tl_module"]["pagesource"]["0"] = "Pages";
$GLOBALS["TL_LANG"]["tl_module"]["pagesource"]["1"] = "Veuillez sélectionner la page qui doit être utilisée pour générer la liste d'objets. Si la page possède des sous-pages, celles-ci seront également utilisées pour la génération de la liste d'objets.";
$GLOBALS["TL_LANG"]["tl_module"]["hide_on_empty"]["0"] = "Toujours filtrer par mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["hide_on_empty"]["1"] = "La liste globale des articles attend toujours au moins un mot-clé pour le filtrage. Sans mot-clé indiqué, une liste vide est affichée.";
$GLOBALS["TL_LANG"]["tl_module"]["articlelist_template"]["0"] = "Modèle de liste d'articles";
$GLOBALS["TL_LANG"]["tl_module"]["articlelist_template"]["1"] = "Ici, vous pouvez choisir le modèle de liste d'articles.";
$GLOBALS["TL_LANG"]["tl_module"]["cloud_template"]["0"] = "Modèle de nuage de mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["cloud_template"]["1"] = "Ici, vous pouvez choisir le modèle de nuage de mots-clés.";
$GLOBALS["TL_LANG"]["tl_module"]["scope_template"]["0"] = "Modèle pour les mots-clés utilisés";
$GLOBALS["TL_LANG"]["tl_module"]["scope_template"]["1"] = "Ici, vous pouvez choisir le modèle pour les mots-clés utilisés.";
$GLOBALS["TL_LANG"]["tl_module"]["clear_text"]["0"] = "Titre des mots-clés utilisés";
$GLOBALS["TL_LANG"]["tl_module"]["clear_text"]["1"] = "Veuillez saisir un titre pour les mots-clés utilisés. Le titre sert également d'hyperlien pour supprimer tous les mots-clés actuellement définis.";
$GLOBALS["TL_LANG"]["tl_module"]["show_empty_scope"]["0"]  = "Toujours afficher les mots-clés utilisés";
$GLOBALS["TL_LANG"]["tl_module"]["show_empty_scope"]["1"]  = "Affiche les mots-clés utilisés même si aucune distinction n'est sélectionnée.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_show_reset"]["0"]  = "Réinitialiser les mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_show_reset"]["1"]  = "Propose un lien hypertexte permettant de réinitialiser les mots-clés sélectionnés.";
$GLOBALS["TL_LANG"]["tl_module"]["tag_alltags"] = "Tous les mots clés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_relatedtags"] = "Mots-clés associés";
$GLOBALS["TL_LANG"]["tl_module"]["tl_content"] = "Éléments de contenu";
$GLOBALS["TL_LANG"]["tl_module"]["tl_article"] = "Article";
$GLOBALS["TL_LANG"]["tl_module"]["tl_news"] = "Articles d'actualité";
$GLOBALS["TL_LANG"]["tl_module"]["tl_calendar_events"] = "Dates";
$GLOBALS["TL_LANG"]["tl_module"]["tl_page"] = "Pages";
$GLOBALS["TL_LANG"]["tl_module"]["showtags_legend"] = "Paramètres des mots-clés";
$GLOBALS["TL_LANG"]["tl_module"]["size_legend"] = "Nombre et paramètres de taille";
$GLOBALS["TL_LANG"]["tl_module"]["tagextension_legend"] = "Listes de mots-clés supplémentaires";
$GLOBALS["TL_LANG"]["tl_module"]["datasource_legend"] = "Paramètres de la source de données";
$GLOBALS["TL_LANG"]["tl_module"]["tagscope_legend"] = "Paramètres pour les mots-clés utilisés";
$GLOBALS["TL_LANG"]["tl_module"]["tag_clear_tags"] = "Réinitialiser les mots-clés sélectionnés";
$GLOBALS["TL_LANG"]["tl_module"]["object_selection_legend"] = "Types d'objets";
$GLOBALS["TL_LANG"]["tl_module"]["tags"] = "Mots clés";
$GLOBALS["TL_LANG"]["tl_module"]["top_tags"] = "Les %s mots-clés les plus fréquents";

// articles

$GLOBALS["TL_LANG"]["tl_module"]["tag_articles"]["0"] = "Article";
$GLOBALS["TL_LANG"]["tl_module"]["tag_articles"]["1"] = "Veuillez sélectionner la page dont les articles doivent être utilisés pour générer le nuage de mots-clés. Si la page possède des sous-pages, ces articles seront également utilisés pour générer le nuage de mots-clés.";
$GLOBALS["TL_LANG"]["tl_module"]["show_in_column"]["0"] = "Limiter la sélection à une colonne spécifique";
$GLOBALS["TL_LANG"]["tl_module"]["show_in_column"]["1"] = "Limitez la sélection de la liste d'articles aux articles d'une colonne spécifique d'un modèle de page.";
$GLOBALS["TL_LANG"]["tl_module"]["linktoarticles"]["0"] = "Liens vers des articles";
$GLOBALS["TL_LANG"]["tl_module"]["linktoarticles"]["1"] = "Sélectionnez cette option si vous souhaitez que les liens avancés de la liste d'articles renvoient aux articles ou désélectionnez cette option pour renvoyer aux pages de contenu des articles.";
$GLOBALS["TL_LANG"]["tl_module"]["restrict_to_column"]["0"] = "Limiter la sélection à une colonne spécifique";
$GLOBALS["TL_LANG"]["tl_module"]["restrict_to_column"]["1"] = "Limitez le nuage de tags aux mots-clés des articles d'une colonne spécifique d'un modèle de page.";
$GLOBALS["TL_LANG"]["tl_module"]["articlelist_tpl"]["0"] = "Modèle de liste d'articles";
$GLOBALS["TL_LANG"]["tl_module"]["articlelist_tpl"]["1"] = "Ici, vous pouvez choisir le modèle de liste d'articles.";
$GLOBALS["TL_LANG"]["tl_module"]["article_showtags"]["0"] = "Afficher les mots-clés de l'article";
$GLOBALS["TL_LANG"]["tl_module"]["article_showtags"]["1"] = "Sélectionnez cette option pour afficher les mots-clés associés à un article sous l'article. Cette option ne fonctionne que si vous utilisez un modèle d'article prévu pour l'édition de mots-clés, comme par exemple mod_global_articlelist";
$GLOBALS["TL_LANG"]["tl_module"]["articlelist_firstorder"] = array("Premier critère de tri", "Sélectionnez le premier critère de tri pour la liste d'articles.");
$GLOBALS["TL_LANG"]["tl_module"]["articlelist_secondorder"] = array("Deuxième critère de tri", "Sélectionnez le deuxième critère de tri pour la liste d'articles.");

// content

$GLOBALS["TL_LANG"]["tl_module"]["tag_content_pages"]["0"] = "Pages";
$GLOBALS["TL_LANG"]["tl_module"]["tag_content_pages"]["1"] = "Veuillez sélectionner la page dont les éléments de contenu doivent être utilisés pour générer le nuage de mots-clés. Si la page possède des sous-pages, ces éléments de contenu seront également utilisés pour générer le nuage de mots-clés.";

// events

$GLOBALS["TL_LANG"]["tl_module"]["tag_calendars"]["0"] = "Calendrier";
$GLOBALS["TL_LANG"]["tl_module"]["tag_calendars"]["1"] = "Veuillez sélectionner les calendriers qui doivent être utilisés pour l'affichage du nuage de mots-clés.";

// members

$GLOBALS["TL_LANG"]["tl_module"]["tag_membergroups"]["0"] = "Groupes de membres";
$GLOBALS["TL_LANG"]["tl_module"]["tag_membergroups"]["1"] = "Veuillez sélectionner un ou plusieurs groupes de membres à partir desquels le nuage de mots-clés doit être généré.";

// news

$GLOBALS["TL_LANG"]["tl_module"]["tag_news_archives"]["0"] = "Limitation aux archives de messages";
$GLOBALS["TL_LANG"]["tl_module"]["tag_news_archives"]["1"] = "Veuillez sélectionner les archives de messages dont les distinctions doivent être utilisées pour le nuage de mots-clés.";

?>
