<?php 

/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_module.php 
 * 
 * Contao extension: tags
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */


/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['tag_jumpTo']          = array('Aller à la page', 'Ce paramètre définit vers quelle page un utilisateur sera redirigé en cliquant sur un lien d\'un tag.');
$GLOBALS['TL_LANG']['tl_module']['tag_forTable']        = array('Table de tags', 'Veuillez sélectionner les tables qui sont utilisées pour afficher le nuage de tags. Cette sélection n\'est valide que si vous utilisez la table <em>tl_tag</em> pour stocker les tags.');
$GLOBALS['TL_LANG']['tl_module']['tag_tagtable']        = array('Table sources des tags', 'Veuillez entrer le nom de la table source dans laquelle les tags peuvent être trouvées. Ce champ utilise par défaut la table prédéfinie <em>tl_tag</em>.');
$GLOBALS['TL_LANG']['tl_module']['tag_tagfield']        = array('Champ de la table de tags', 'Veuillez entrer le nom du champ de table qui contient les tags. Ce champ prend par défaut le nom de champ prédéfini <em>tag</em>.');
$GLOBALS['TL_LANG']['tl_module']['tag_filter']          = array('Filtre de tags', 'Veuillez entrer une liste de tags séparés par des virgules pour filtrer la sortie du module.');
$GLOBALS['TL_LANG']['tl_module']['tag_maxtags']         = array('Nombre maximal de tags', 'Veuillez saisir le nombre maximum de tags dans le nuage de tags. Si le nuage de tags contient plus de tags que le nombre maximal, les tags avec le plus petit nombre de correspondances seront supprimées du nuage. Si vous n\'entrez pas de valeur ou si la valeur est 0, tous les tags seront affichés.');
$GLOBALS['TL_LANG']['tl_module']['tag_buckets']         = array('Nombre de tailles de balises', 'Veuillez saisir le nombre de tailles de balises dans l\'interface. Chaque groupe de tags obtient sa propre taille de balise dans le frontend. Les tailles des balises seront données sous forme de sélecteurs CSS size1, size2, size3 ... size<em>n</em>.');
$GLOBALS['TL_LANG']['tl_module']['tag_named_class']     = array('Ajouter des class CSS aux tags', 'Ajoute une classe CSS supplémentaire pour chaque tag contenant le nom du tag. Utilisez ces noms de classes supplémentaires pour mettre en page via CSS. Les espaces dans les noms de tags seront remplacés par des underscore dans les noms de classe CSS.');
$GLOBALS['TL_LANG']['tl_module']['tag_on_page_class']   = array('Le tag existe sur la page', 'Ajoute une classe CSS supplémentaire (\'here\') pour chaque tag qui a été affectée à la page en affichées.');
$GLOBALS['TL_LANG']['tl_module']['tag_topten']          = array('Top tags', 'Affichez les tags les plus utilisés au-dessus du nuage de tags.');
$GLOBALS['TL_LANG']['tl_module']['tag_topten_expanded'] = array('Développer les top Tags', 'Tous les tags de ce nuage sont visibles par defaut');
$GLOBALS['TL_LANG']['tl_module']['tag_topten_number']   = array('Nombre de tags dans le Top', 'Entrez le nombre maximum de tags visibles pour les Top Tags.');
$GLOBALS['TL_LANG']['tl_module']['tag_all_expanded']    = array('Développer tous les Tags', 'Tous les tags de ce nuage sont visibles.');
$GLOBALS['TL_LANG']['tl_module']['tag_related']         = array('Afficher les tags associées', 'Actyivez cette option pour afficher toutes les tags associés d\'un tag précédemment sélectionné.');
$GLOBALS['TL_LANG']['tl_module']['news_showtags']       = array('Afficher les tags d\'actualité', 'Actyivez cette option pour afficher tous les tags attribués aux actualités. Cela ne fonctionne que si vous utilisez un template d\'actualités compatible avec les tags, e.g. news_full_tags');
$GLOBALS['TL_LANG']['tl_module']['event_showtags']       = array('Afficher les tags des événement', 'Actyivez cette option pour afficher toutes les tags attribués aux événements. Cela ne fonctionne que si vous utilisez un template d\'événement compatible avec les tags, e.g. event_..._tags');
$GLOBALS['TL_LANG']['tl_module']['tag_ignore']          = array('Ignorer les tags', 'Forcer ce module à ignorer les actions liées aux tags(e.g. afficher uniquement les actualités d\'un tag selectionné)');
$GLOBALS['TL_LANG']['tl_module']['keep_url_params']     = array('Conserver les paramètres de l\'URL', 'Conserver les paramètres de l\'URL spécifiques à Contao (e.g. paramètres de date des archives d\'actualités) dans le lien du tag');
$GLOBALS['TL_LANG']['tl_module']['objecttype']          = array('Type d\'objet', 'Veuillez sélectionner le type d\'objet qui doit être affiché dans cette liste.');
$GLOBALS['TL_LANG']['tl_module']['tagsource']           = array('Source des tags', 'Veuillez sélectionner la table utilisée pour créer la liste de tags dans ce module.');
$GLOBALS['TL_LANG']['tl_module']['pagesource']          = array('Pages', 'Veuillez sélectionner les pages utilisées pour créer la liste d\'objets. Si vous sélectionnez une page qui contient des sous-pages, toutes les sous-pages seront également utilisées.');
$GLOBALS['TL_LANG']['tl_module']['articlelist_template'] = array('Articlelist template', 'Ici, vous pouvez sélectionner le template de liste d\'articles.');
$GLOBALS['TL_LANG']['tl_module']['cloud_template']      = array('Template du nuage de tags', 'Ici, vous pouvez sélectionner le template du nuage de tags.');
$GLOBALS['TL_LANG']['tl_module']['scope_template']      = array('Template de la portée des tags', 'Ici, vous pouvez sélectionner le template de la portée des tags.');
$GLOBALS['TL_LANG']['tl_module']['clear_text']          = array('Titre de la portée des tags', 'Saisissez un titre pour la porté des tags. Ce titre s\'affiche sous forme d\'un lien de réinitialisation de la portée des tags et supprime tous les tags actifs filtrant les résultats.');
$GLOBALS['TL_LANG']['tl_module']['show_empty_scope']    = array('Afficher la porté même si elle est vide', 'Affiche la porté des tags même si aucun tag n\'est actif');
$GLOBALS['TL_LANG']['tl_module']['tag_show_reset']      = array('Afficher un lien de réinitialisation', 'Afficher un lien pour réinitialiser tous les tags sélectionnés.');
$GLOBALS['TL_LANG']['tl_module']['hide_on_empty']       = array('Sortie filtrée uniquement', 'La liste d\'articles globale s\'attend toujours à ce qu\'un ou plusieurs tags produisent une sortie filtrée. Sans filtre de tags, une liste vide s\'affiche.');
$GLOBALS['TL_LANG']['tl_module']['tag_alltags']         = 'Tous les tags';
$GLOBALS['TL_LANG']['tl_module']['tag_relatedtags']     = 'Tags associés';
$GLOBALS['TL_LANG']['tl_module']['tl_content']          = "Éléments de contenu";
$GLOBALS['TL_LANG']['tl_module']['tl_article']          = "Articles";
$GLOBALS['TL_LANG']['tl_module']['tl_news']             = "Articles d\'actualités";
$GLOBALS['TL_LANG']['tl_module']['tag_clear_tags']      = "Réinitialiser les tags";
$GLOBALS['TL_LANG']['tl_module']['tl_calendar_events']  = "Événements";
$GLOBALS['TL_LANG']['tl_module']['tl_page']             = "Pages";
$GLOBALS['TL_LANG']['tl_module']['tags']                = "Tags";
$GLOBALS['TL_LANG']['tl_module']['top_tags']            = 'Top %s Tags';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['showtags_legend']         = 'Paramètres des tags';
$GLOBALS['TL_LANG']['tl_module']['tagscope_legend']         = 'Paramètres de la portée des tags';
$GLOBALS['TL_LANG']['tl_module']['size_legend']         = 'Paramètres de nombre et de tailles';
$GLOBALS['TL_LANG']['tl_module']['tagextension_legend'] = 'Listes de tags supplémentaires';
$GLOBALS['TL_LANG']['tl_module']['datasource_legend'] = 'Paramètres de la source de données';
$GLOBALS['TL_LANG']['tl_module']['object_selection_legend'] = "Type d'objet";

// articles

$GLOBALS['TL_LANG']['tl_module']['tag_articles']   = array('Articles', 'Veuillez sélectionner les pages dont les articles sont utilisés pour construire le nuage de tags. Si vous cochez une page qui contient des sous-pages, les articles de toutes les sous-pages seront également utilisés.');
$GLOBALS['TL_LANG']['tl_module']['show_in_column'] = array('Restreindre à des colonnes spécifiques', 'Limitez la sortie de la liste d\'articles à une colonne spécifique du template de la page.');
$GLOBALS['TL_LANG']['tl_module']['linktoarticles'] = array('Liste des liens d\'articles vers des articles', 'Cochez pour créer une liste d\'articles avec des liens vers l\'article ou décochez pour créer une liste d\'articles avec des liens vers la page de contenu.');
$GLOBALS['TL_LANG']['tl_module']['restrict_to_column'] = array('Restreindre à des colonnes spécifiques', 'Limitez le nuage de tags aux tags des articles d\'une colonne spécifique du template de la page.');
$GLOBALS['TL_LANG']['tl_module']['articlelist_tpl'] = array('Template de la liste d\'articles', 'Ici, vous pouvez sélectionner le template de la liste d\'articles.');
$GLOBALS['TL_LANG']['tl_module']['article_showtags']       = array('Afficher les tags des articles', 'Sélectionnez cette option pour afficher tous les tags attribués à chaque article. Cela ne fonctionne que si vous utilisez un template d\'article compatible avec les tags, e.g. mod_global_articlelist');
$GLOBALS['TL_LANG']['tl_module']['articlelist_firstorder'] = array('Premier critère de tri', 'Sélectionnez le premier critère de tri pour la liste d\'articles résultante.');
$GLOBALS['TL_LANG']['tl_module']['articlelist_secondorder'] = array('Deuxième critère de tri', 'Sélectionnez le deuxième critère de tri pour la liste d\'articles résultante.');

// content

$GLOBALS['TL_LANG']['tl_module']['tag_content_pages']   = array('Pages', 'Veuillez sélectionner les pages dont les éléments de contenu sont utilisés pour créer le nuage de tags. Si vous sélectionnez une page qui contient des sous-pages, les éléments de contenu de toutes les sous-pages seront également utilisés.');

// events

$GLOBALS['TL_LANG']['tl_module']['tag_calendars']   = array('Calendriers', 'Veuillez sélectionner les calendriers qui sont utilisés pour construire le nuage de tags.');

// members

$GLOBALS['TL_LANG']['tl_module']['tag_membergroups']   = array('Groupes de membres', 'Veuillez sélectionner un ou plusieurs groupes de membres pour créer le nuage de tags de membres.');

// news

$GLOBALS['TL_LANG']['tl_module']['tag_news_archives']   = array('Archives des actualités', 'Veuillez sélectionner les archives d\'actualités qui sont utilisées pour construire le nuage de tags.');

?>
