<?php
/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_settings.php
 *
 * Contao extension: tags
 * French translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */
 
$GLOBALS["TL_LANG"]["tl_settings"]["disabledTagObjects"]["0"] = "Sources de mots-clés désactivées";
$GLOBALS["TL_LANG"]["tl_settings"]["disabledTagObjects"]["1"] = "Sélectionnez tous les tableaux de données pour lesquels aucun champ de saisie de mot-clé ne doit être disponible dans le backend.";
$GLOBALS["TL_LANG"]["tl_settings"]["tags_legend"] = "Paramètres des mots-clés";
 
?>
