<?php 

/**
 * TL_ROOT/system/modules/tags/languages/fr/tl_settings.php 
 * 
 * Contao extension: tags
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['tl_settings']['disabledTagObjects']    = array('Désactiver la table source des tags', 'Vérifiez toutes les tables source qui ne doivent pas avoir de champ de saisie de tags dans le backend.');
$GLOBALS['TL_LANG']['tl_settings']['tags_legend']    = 'Paramètre des tags';

?>