<?php

/**
 * TL_ROOT/system/modules/tags/languages/de/tl_article.php
 *
 * Contao extension: tags
 * German translation file
 *
 * Copyright : &copy; Helmut Schottmüller
 * License   : GNU Lesser Public License (LGPL)
 * Author    : Helmut Schottmüller (hschottm), https://github.com/hschottm
 * Translator: Helmut Schottmüller (hschottm), https://github.com/hschottm
 *
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */


/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_article']['tags_jumpto']         = array('Weiterleitung zu Seite', 'Mit dieser Einstellung legen Sie fest, auf welche Seite ein Benutzer nach dem Anklicken einer Auszeichnung weitergeleitet wird.');
$GLOBALS['TL_LANG']['tl_article']['tags_max_tags']       = array('Maximale Anzahl von Auszeichnungen', 'Geben Sie die maximale Anzahl an Auszeichnungen an, die zu diesem Artikel angezeigt werden sollen. Ist die maximale Anzahl gleich 0, so werden alle Auszeichnungen angezeigt.');
$GLOBALS['TL_LANG']['tl_article']['tags_showtags']       = array('Auszeichnungen anzeigen', 'Wählen Sie diese Option, um die zu diesem Artikel zugehörigen Auszeichnungen anzuzeigen.');
$GLOBALS['TL_LANG']['tl_article']['tags_relevance']      = array('Nach Relevanz sortieren', 'Wählen Sie diese Option, um die zu diesem Artikel zugehörigen Auszeichnungen nach Relevanz (Häufigkeit ihres Auftretens) zu sortieren. Wenn diese Option nicht ausgewählt ist, werden die Auszeichnungen alphabetisch sortiert.');
$GLOBALS['TL_LANG']['tl_article']['tags']                = "Auszeichnungen";

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_article']['tags_legend']         = 'Auszeichnungen';

?>